//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionStock.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VlisteVente
    {
        public int id { get; set; }
        public string CodeProduitV { get; set; }
        public string DesignationProduitV { get; set; }
        public Nullable<double> PuProduitV { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Tel { get; set; }
        public string AdresseEmail { get; set; }
    }
}
